import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import { Button, Text } from '@nextui-org/react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Cheng's Photography Website</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <>
          <Text
            h1
            size={60}
            css={{
              textGradient: '45deg, $blue600 -20%, $pink600 50%',
            }}
            weight='bold'
          >
            Let's
          </Text>
          <Text
            h1
            size={60}
            css={{
              textGradient: '45deg, $purple600 -20%, $pink600 100%',
            }}
            weight='bold'
          >
            Make the Web
          </Text>
          <Text
            h1
            size={60}
            css={{
              textGradient: '45deg, $yellow600 -20%, $red600 100%',
            }}
            weight='bold'
          >
            Prettier
          </Text>
        </>
      </div>
    </>
  );
}
