import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import NavbarNext from '@/components/NavbarNext';
import Gallery from '@/components/Gallery';
import test from '../public/test.jpg';
import img1 from '../public/1.jpg';
import img2 from '../public/2.jpg';
import img3 from '../public/3.jpg';
import img4 from '../public/4.jpg';
import img5 from '../public/5.jpg';

const images = [
  {
    id: 1,
    src: img1,
    alt: 'Image 1',
  },
  {
    id: 2,
    src: img2,
    alt: 'Image 2',
  },
  {
    id: 3,
    src: img3,
    alt: 'Image 3',
  },
  {
    id: 4,
    src: img4,
    alt: 'Image 4',
  },
  {
    id: 5,
    src: img5,
    alt: 'Image 5',
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Cheng Lim Photography</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavbarNext />
      <Gallery images={images} />
    </>
  );
}
