import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import Navbar from '@/components/Navbar';
import Gallery from '@/components/Gallery';
import test from '../public/test.jpg';

const images = [
  {
    id: 1,
    src: { test },
    alt: 'Image 1',
  },
  {
    id: 2,
    src: { test },
    alt: 'Image 2',
  },
  {
    id: 3,
    src: { test },
    alt: 'Image 3',
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <Gallery images={images} />
    </>
  );
}
